### ISSUE TITLE
Review exposed types and methods

### ISSUE THREAD

**Issue by embano1** [timbray/quamina#10]
After the restructuring IMHO it would make sense to review all exposed types, vars, functions and methods to verify:

a) they have to be exposed (you know, part of the API, breaking changes, etc.)
b) all exposed objects have proper code comments/follow Go conventions regarding naming

**Comment by timbray** [comment]
Agreed.  I changed my mind a few times while writing the code and I expect there are some things inappropriately exposed.

**Comment by timbray** [comment]
I've cleaned up the `core` side - @jsmorph, looks to me like there a few things that could be unexposed on the `pruner` side.
