### ISSUE TITLE
code: Adopt AWS Event Ruler unit tests

### ISSUE THREAD

**Issue by timbray** [timbray/quamina#144]
There is a huge amount of accumulated wisdom in https://github.com/aws/event-ruler/tree/main/src/test/software/amazon/event/ruler as a consequence of running at millions of invocations / second for years.  We should cherry-pick a few. I bet this will turn up deep horrifying bugs in Quamina and learn useful things.

**Comment by jsmorph** [comment]
That is a big event [right there](https://github.com/aws/event-ruler/blob/main/src/test/data/bigEvent.json)! Excellent.

**Comment by embano1** [comment]
> That is a big event [right there](https://github.com/aws/event-ruler/blob/main/src/test/data/bigEvent.json)! Excellent.

Wow, `25581` bytes what a surprise :)

`"Do not use to reconstruct hosted zone"` :D
