### ISSUE TITLE
bug: Quote escaping termination failure

### ISSUE THREAD

**Issue by crossjam** [timbray/quamina#150]
v0.3.0 of quamina, go 1.19

In building a toy, line oriented cli for quamina, I fed the library JSON data from https://www.gharchive.org/ and generated failures with the following message:
`at line 1 col 15: truncated string`. The following reductionist (but valid) JSON triggers the error
```
{ "message" : "docs: change \" -> \\" }
```

The quamina rule being processed is:
```
{"type": ["PublicEvent"]}
```
although I think the pattern is immaterial.

Adding a space after the last \\ in the example JSON allows for successful processing.

I have a longer chunk of probably awful, newbie Go code that implements the cli binary, but I'll abstain from posting here unless requested.

**Comment by yosiat** [comment]
Hey

This happens only in v0.3.0 since we introduce fast way to skip string values, I did a PR to fix this issue - https://github.com/timbray/quamina/pull/151
