### ISSUE TITLE
broken badges

### ISSUE THREAD

**Issue by timbray** [timbray/quamina#16]
The "go report" and "Go v1.18" badges are broken.

**Comment by embano1** [comment]
Hm, they look good to me. Sometimes a reload fixes it because the underlying remote call timed out.

**Comment by timbray** [comment]
![aplus](https://user-images.githubusercontent.com/17555/170430175-7bd132d4-60a7-46b5-b1e3-be6da8696387.jpg)

**Comment by timbray** [comment]
![1 18](https://user-images.githubusercontent.com/17555/170430527-6372e66c-6316-4b5b-81e7-69ab35e4c201.jpg)

**Comment by timbray** [comment]
Those two are the output I get when clicking on the A+ and 1.18 badges

**Comment by embano1** [comment]
Ah, sorry. Misread your issue here (thought the badges were not showing up). Will fix.

**Comment by timbray** [comment]
What is the “Go 1.18” for and what is it supposed to do.

**Comment by embano1** [comment]
It directly highlights the recommended (minimal) required go version to use this library without needing to check `go.mod`. https://go.dev/ref/mod#go-mod-file-go

**Comment by timbray** [comment]
OK
