### ISSUE TITLE
Fix unit-test CI

### ISSUE THREAD

**Issue by timbray** [timbray/quamina#172]
Currently the GitHub task that runs the unit tests fails with the message mentioning "error code 143".  This turns out to be an acknowledged problem in GitHub, see https://github.com/actions/runner-images/issues/6680#issuecomment-1335778010

The unit tests pass reliably on "normal" computers.

Perhaps restructuring the GitHub tasks and using Go build tags will address this problem.

**Comment by timbray** [comment]
This problem occurred when we added the borrowed-from-Ruler tests `cl2_test.go` and `generic_machine_test.go`.  So the hypothesis is that these tests pushed the GitHub infrastructure into overload. I can see two ways that this could be addressed:

* put those tests in a different package - would want to talk about how to structure folders and so on
* put a build tag `//go:build fromRuler` on those tests, and `//go:build !fromRuler` on all the others, then have two different GitHub tasks workflows, one with `-tags=fromRuler` and one without.

As an interim measure I guess I can just put the `fromRuler` tag on the two files and make a little PR to see whether the in the PR validation, the unit-test step actually passes.  I'll do that.

**Comment by timbray** [comment]
Yay, #173 seems to fix this.  Now, it does mean that two quite useful unit tests are not being run.  We should probably update the instructions in CONTRIBUTING.md to say "please run unit tests with `-tags=fromRuler`".  

Since the unit-test coverage is still excellent without these tests, I think I'd like to go ahead and merge this, and then file a new issue to figure out how to get these back into the CI.

**Comment by embano1** [comment]
This is OK with me. We could create a second workflow only running specific go tests (since we can't easily exclude those without build tags). Gets a bit tricky if we change the tests in `fromRuler`, but better than not running them at all IMHO.
