### ISSUE TITLE
Add context.Context arg to Matcher methods?

### ISSUE THREAD

**Issue by jsmorph** [timbray/quamina#25]
Should Matcher interface methods take [`context.Context`](https://pkg.go.dev/context)s as their first arguments?

Rationale: Some underlying implementations (e.g., `Pruner` with `State` that does I/O) might want to have a context (for either timeouts/deadlines or context [values](https://pkg.go.dev/context#WithValue)), and some fancy matchers that do async/background work might want a context for timeouts in `select`s.

**Comment by timbray** [comment]
I'm dubious on this one.  Context tries to be a general-purpose, uh, something, but in my experience I've only ever seen it used for timeout handling.  At the moment, I feel that any time someone calls into Quamina and has to handle timeouts, we've probably failed.  This isn't a one-way door, I've seen plenty of APIs that exist in regular and withContext variations.

**Comment by embano1** [comment]
My pov:

`core.Matcher` seems to be OK without `ctx` as it has a behavior similar to `io.Reader|Writer` which also don't have `ctx` but are typically wrapped into ones with `ctx` if required. 

For `pruner.Matcher` I am not sure whether we're purely talking in-mem implementations here (i.e. low-latency/fast returns) or I/O variants (incl. networking). If so, a caller could still use a custom constructor or implement async style on her own as encouraged by the Go community for pkg-level APIs.

I understand that adding `ctx` later is a breaking change, though we're still not `v1` stable and haven't gotten much feedback on how the package is used in the wild. To avoid breaking changes, we could add `WithContext` functions/methods later as Tim suggests if that's a requirement.

**Comment by timbray** [comment]
I agree.  Let's leave the door open for *WithContext flavors of the APIs in future.
