### ISSUE TITLE
addPattern: index out of range 

### ISSUE THREAD

**Issue by daxzhuo** [timbray/quamina#252]
version v1.0.0
code position
https://github.com/timbray/quamina/blob/v1.0.0/core_matcher.go#L89C18-L89C18

if vals is empty will trigger an index out of range

testing pattern
```{"data": {"field": []}}```

**Comment by timbray** [comment]
Oops, that looks like a bug. Thanks. Will dig in and fix.

**Comment by timbray** [comment]
Fixed in #258
