### ISSUE TITLE
Codecov action not running?

### ISSUE THREAD

**Issue by embano1** [timbray/quamina#309]
Just noticed this note in the unit tests in PR #308:

> Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/125fc84a9a348dbcf27191600683ec096ec9021c/dist/codecov' failed with exit code 1

**Comment by embano1** [comment]
Seems something changed in Codecov requiring token:

> Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/125fc84a9a348dbcf27191600683ec096ec9021c/dist/codecov' failed with exit code 1

Will investigate

**Comment by timbray** [comment]
Oh, will investigate too.  I had the same problem on topfew and figured it out. But wait, the actions report said everything passed?!?!

**Comment by timbray** [comment]
OK, you have to go in the settings for "Secrets and Variables" and set up a "repository secret", which I did.  Is there a way to force the actions to re-run without pushing something?

**Comment by timbray** [comment]
I will have a look, but first, how do you re-run the PR checks?

**Comment by embano1** [comment]
See `Re-run all Jobs` button

<img width="1658" alt="image" src="https://github.com/timbray/quamina/assets/15986659/8b61d916-f815-48cd-b8fc-c0fefb01f01f">

**Comment by embano1** [comment]
> Oh, will investigate too. I had the same problem on topfew and figured it out. But wait, the actions report said everything passed?!?!

Guess the action is configured to not fail the workflow on error

**Comment by timbray** [comment]
Well, per the instructions at https://docs.codecov.com/docs/adding-the-codecov-token I added
```yaml
env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

And that certainly changed things. It found the token, lots of failures saying token validation failed.  I went and regenerated the token over at Codecov, updated the repository secret at GitHub.  Not sure what to do next, will take a break and research some more.

**Comment by timbray** [comment]
Hmm, I notice that they're talking about codecov-action@4 in the docs page, our codecov point release is still 3.something. Worth bumping to @4?

**Comment by embano1** [comment]
Yeah, let's try that!

**Comment by embano1** [comment]
Ah, looks like it's working [now](https://github.com/timbray/quamina/actions/runs/9260658884/job/25475012634#step:8:50). Closing issue.
