### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by timbray** [timbray/quamina#33]
Coverage is only 83% overall, not good enough.  The main culprit is lack of tests that check error returns, especially in fj.go, which is a huge file and doesn't have tests for any of the very large number of possible syntax errors.  Also numbers.go is very weak (even though it is not actually in production yet).

**Comment by timbray** [comment]
Let this be a lesson for all of us.  The best way to improve coverage is to throw a bunch of broken-JSON test cases at flattenJSON, because none of the error exits had test coverage.  In doing this, I ran across several nasty bugs in JSON number parsing, that someone would certainly have hit before too long.  *blushes*

**Comment by jsmorph** [comment]
Maybe there's a place for Go's new [fuzz testing](https://go.dev/doc/fuzz/) somewhere around here.

**Comment by timbray** [comment]
Hmm… quote:
The fuzzing arguments can only be the following types:
* string, []byte
* int, int8, int16, int32/rune, int64
* uint, uint8/byte, uint16, uint32, uint64
* float32, float64
* bool

What we need is to generate random JSON, in effect.  https://github.com/timbray/quamina/blob/main/value_matcher_test.go has a couple of hand-built fuzz tests for matching random strings and numbers and I can see how I could have done that easier with the new capability. Will keep a lookout for opportunities.

**Comment by jsmorph** [comment]
My little https://github.com/jsmorph/corpusgen can generate semi-random JSON. Could stand some usability and doc improvements. I'll see if I can clean that up.
