### ISSUE TITLE
api: Relationship between Flatteners and Matchers

### ISSUE THREAD

**Issue by timbray** [timbray/quamina#34]
I'm worried about getting into one of those hideous Go circular-dependency traps.  Let me describe the situation in free text in hopes of clearing up my own thinking and provoking suggestions on the right way forward.

After a Matcher has been loaded with Patterns, every Event has to be flattened before it can be used with a Matcher call to find which patterns match it.

Both Matcher and Flattener are interfaces, both currently defined in core/.  We already have two implementations of Matcher (in core/ and pruner/) but only one implementation of Flattener (core/FJ).  I think it is very likely that we will have multiple flatteners in future - for Avro, Protobufs, CBOR, etc etc.  

In theory, Matchers and Flatteners don't need to know about each other. A Flattener gets a []byte message in some form and emits a []*Field. Hmm, just realized they both need to know about Field.  

A Flattener does need to know which Field names are used in patterns, so it can leave the rest out of the []Field output - this is a really important optimization.  In practice this has to be provided by a Matcher because it knows what fields are used as a result of all the AddPattern() calls.  There is an interface called NameTracker with one method, IsNameUsed(string name), which in theory should be used by FJ but at the moment it isn't, NewFJ() is given a CoreMatcher, which it uses both for the IsNameUsed call and for the FlattenAndMatch convenience function. So that interface needs to be either used or discarded.

I want to make it easy and straightforward to add a new Flattener for a new data type and now I'm thinking of how to organize things to achieve that. Conceivably the new Flattener shouldn't even have to be part of this repo.  Two approaches occur to me:

1. Leave everything in core/ - minimum hassle and risk of circular dependencies.  But, is it still straightforward to implement a new Flattener?
2. Make new subdirectories for at least Matcher, Flattener, Field.  You wouldn't get a convenience function like flattener.FlattenAndMatch() but everything would be maximally clean. I'd lose sleep about wandering into a circular dependency.

Anyhow, at least I've written the problem down now. Input at any level from comprehensive suggestions to "at least don't do X" would be welcome.

**Comment by jsmorph** [comment]
Maybe:

1. package `matching`: interfaces like `Flattener` and `Matcher` (and maybe `NameTracker`) and some shared primitive types like `Field`.
2. package `core` for the core Matcher implementation.
3. `flatterners/json` for `FJ`. (Maybe not "json" for the package name.)
4. package `pruner` for the Pruner implementation -- pretty much as is.

Variation: Instead of `core` and `pruner`: `matchers/core` and `matchers/pruner`:

```
matching
testing/concurrent
testing/verymean
testing/longrunning
flatteners/json
flatteners/protobuf
matchers/core
matchers/pruner
matchers/quantum
```

**Comment by embano1** [comment]
Btw: I'm a huge fan of using functional options in constructors.

E.g. `NewCoreMatcher()` could become `NewCoreMatcher(opts ...MatcherOpts)`. Then you range over the `opts` and use default values if none are passed (i.e. `nil`). Example here (see `filters` parameter): https://github.com/embano1/vsphere/blob/dea45480357a69533b6326e1218ca128e049215f/event/event.go#L15

**Comment by timbray** [comment]
I thought about this a lot last night and I *think* I have an idea. @embano1 you did the right thing by trying a refactor so let me do that too.  

Here's what I think might work:
/control
/core
/pruner
/fields
/flatteners

The idea is that 
/core only knows about `AddPattern()` and `MatchFields()`
/flattener only knows about `Flatten()` 
/fields basically only has the type definition and the ugly `ArrayTrailConflict` stuff, so core Matcher is a little easier to read
/pruner is as now (implements `Matcher` interface)
/control makes it all user friendly - provides a way to pick the right flattener (JSON, Avro, etc) and matcher (core or pruner) and then offers a single `MatchsForEvent()` method that takes care of flattening the event and passing the fields to the matcher.  There's a no-options default that uses FJ and core Matcher, but setting up to use a Protobufs flattener and pruner matcher is just a couple of options tweaks.


I think this avoids circular dependencies… and makes it easy to write new Flatteners, etc.  But let me try.

**Comment by timbray** [comment]
No apologies necessary. The one thing that's most important to me is to rip apart the matching/pattern-adding stuff from the Flattening stuff. It's essential that they be orthogonal.  Neither needs to know the other exists. But, there are a few things they need to both depend on, e.g. the Field and ArrayPos types, and UTF-8 related constants and so on. 

Then, assuming that there are many flavors of Flattener and at least two flavors of Matcher, how do we make this library easy to call?  (a) have reasonable defaults [see quamina/quamina.go  in the recent push] and [not yet done] a version that accepts general-purpose options like you describe.  

Plan B is put everything in one folder quamina/ but I have to convince myself an external author can write a Flattener.  Also, as usual, worried about circularity.

**Comment by timbray** [comment]
OK, had a talk with @embano1 and he convinced me that, as a pure library, we really don't need a directory structure at all, we can just put all the code in the root and in package quamina.  I am a sucker for doing things in the simplest way that could possibly work, so I'll try that refactor next and see how it looks.

**Comment by timbray** [comment]
Hmm, my view is that the top-level interface is in quamina.go, and you’re right, it should be just MatchesForEvent.  There’s no particular reason why the Quamina type needs to have JSON in the name.  If you look at the Quamina struct, it's set up to allow pluggable matcher and flattener.  Still undone: A form of the call that lets you pick those options.

**Comment by timbray** [comment]
… which I guess means that a lot of stuff can be unexposed?  E.g. we can have coreMatcher and prunerMatcher…

**Comment by embano1** [comment]
That's perfect! And yes, we can unexport those because they're not of direct use/need.

Take a look at this prototype using functional options to pass custom `Matcher` and `Flattener`, but using safe defaults :)
https://github.com/timbray/quamina/commit/8fb996496ed1c005159955763c857567cda77f8f
