### ISSUE TITLE
`Flattener` interface `reset` not exported

### ISSUE THREAD

**Issue by embano1** [timbray/quamina#37]
Is this a typo or intentional?

https://github.com/timbray/quamina/blob/875c2690dc820cc9c9203e3fe2a876c3df2f46c6/core/flattener.go#L38

**Comment by embano1** [comment]
Also see this comment: https://github.com/timbray/quamina/issues/34#issuecomment-1140822512

**Comment by timbray** [comment]
I'm pretty sure this is correct.  Flattener can `reset()` itself when it's called, no need for caller to worry about it.

**Comment by embano1** [comment]
Hm, so why is this part of the `interface` definition then? Never seen that pattern before.

**Comment by timbray** [comment]
Heh, it's a bug that it's in the interface
