### ISSUE TITLE
Support for custom functions for pattern checking

### ISSUE THREAD

**Issue by samirsa** [timbray/quamina#39]
Quamina already seems to support the use of some functions to define whether an event can be deemed to match a pattern, such as the "exists" or "shellstyle" functions.

I think that we were to make this user-definable, then it will be a significant addition to the capabilities of quamina in different scenarios, where the native pattern matching does not support that kind of functionality.
A simple example is greater-than,less-than etc. (which of course is trivial to implement for integers, but then those operators can mean different things in different application settings). 

Another simple example of such a user-defined function could be "is-ip-address", "is-part-of-subnet" etc. 

Using such a user-defined function, i am imagining a pattern as follows

```
{"Image": { "Width": [ { "is_greater_than": 200 },  { "is_less_than": 1000 } ] } }
```

I have not yet tested, if Quamina supports multiple such checks, but if they are not supported yet - that could be a different enhancement. 

Quamina could support a new API like registerPatternOperator which will take a keyword ("is_greater_than" in the above example), and a function implementation (subject to the required function signature). In the first iteration, such a function could return a simple boolean (or any additional information that you might need). Based on the response, the core quamina pattern matching engine can deem this sub-pattern to have matched or not.

**Comment by timbray** [comment]
The patterns are based on those of AWS EventBridge: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns.html - still lots of stuff there that Quamina doesn't have yet.  The design can't get too open-ended because for Quamina to meet its performance goals, the patterns need to be compiled into finite automata in a reasonably efficient fashion.

I like the IP address idea.  In particular, how about a CIDR as a query pattern?

**Comment by embano1** [comment]
Related question I had @timbray : how hard would it be to support EB pattern matching (string) import/reuse in quamina? Like one key use case likely will be using quamina to perform local pattern matches before sending it up to EB.

**Comment by timbray** [comment]
That's the idea.  Everything so far in Quamina is EB-compatible, with the exception of the * "shellstyle" pattern, and my belief is that EB would like to have that.  There are some EB pattern features that Quamina doesn't have yet, but we'll get there.

**Comment by embano1** [comment]
That's great news!

**Comment by samirsa** [comment]
Thanks for the update. Looking at the table of operators supported by EB, that looks like a good list for now (though, I would request you to consider custom functions at some point of time)
Coming to the "standard" list of operators, do you plan to add Numeric(equals) and Numeric(range) soon? That would greatly help in some of the use-case that I am looking at.

**Comment by timbray** [comment]
Thanks for that.  There are a lot of things I could choose to work on, and input of the form “X would be useful to us” is helpful in prioritizing.

**Comment by timbray** [comment]
I'm going to close this because realistically, catching up with AWS Event Ruler (and then keeping up) is likely to occupy bandwidth for the foreseeable future.
