### ISSUE TITLE
Remove LFS stuff & citylots.jlines

### ISSUE THREAD

**Issue by timbray** [timbray/quamina#42]
The huge file testdata/citylots.jlines is no longer needed, tests have been updated to use the compressed form. Will remove before too long.  A lot of the CI stuff still has LFS enabled.  Is having that in there a problem, i.e. should we take it out?

**Comment by embano1** [comment]
Happy to take it out if no tests, etc. are using LFS anymore. Just confirm and I'll file PR.

**Comment by timbray** [comment]
I have just verified that all the tests run if testdata/citylines.jlines is removed.  Might as well including removing that in the PR that remove the lFS stuff.
