### ISSUE TITLE
go.mod should define the module name with complete github.com path

### ISSUE THREAD

**Issue by samirsa** [timbray/quamina#5]
It seems that the way the module name is defined in go.mod, it is not possible to easily use this package from other golang projects.
Is there reason, that the module name is not defined as follows?

```
module github.com/timbray/quamina

go 1.18
```

Alternatively, if there is an easy way to use this package without this change, then could it be added to the README?

**Comment by timbray** [comment]
Oh, OK.  I'm weak on Go CI/CD/releasing, but we're working on it.  Changing the go.mod as you recommend breaks some things, we'll fix this up.

**Comment by samirsa** [comment]
Thank you for your prompt response on fixing this.
