### ISSUE TITLE
Clarify supported pattern matchers

### ISSUE THREAD

**Issue by embano1** [timbray/quamina#57]
From the README the following is not clear IMHO:

- Which patterns are supported/implemented?
- That this package follows EventBridge pattern matching, i.e. highlight as feature in README to reuse EB patterns?

Having a table which maps existing patterns, e.g. from EventBridge, to supported/unsupported in the README would be nice, e.g.:

| Pattern | Suppported | Notes |
|---------|------------|-------|
| `exists`         |     Yes       |       |
| `shellstyle`| Yes* | Only single wildcard `*` supported|
| `number`| Yes* | Number matching is weak|

Thoughts?

**Comment by timbray** [comment]
Agreed.
