### ISSUE TITLE
Enable Github Actions

### ISSUE THREAD

**Issue by embano1** [timbray/quamina#6]
As per a discussion with @timbray it would be nice to leverage Github Actions for same basic automation around unit tests, PR reviews, etc. Later this can be extended for release automation, package management (if needed), and so on.

**Comment by embano1** [comment]
@timbray we can also do 1,2,3 and I rebase to keep the PR up2date. Either way works for me. After merging (3) we should enable branch protection rules to ensure PRs must pass certain status checks (actions) before being allowed to merge. (admins can always overrule though if needed)

**Comment by embano1** [comment]
Btw: at some point (perhaps later) you might want nice CHANGELOGs or release notes. This typically requires some effort on commit naming (prefixing)/content. Just wanted to mention here as the more commits you create without a "standardized" (parsable) structure, the harder it gets later to create an automated CHANGELOG/release notes :)

There's multiple options here, let me know if this sounds useful and I can create a separate issue to discuss/raise a PR.

Example: https://github.com/vmware/govmomi/releases

**Comment by timbray** [comment]
Oh yes please, definitely useful, a Issue/PR would be very welcome.
